# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2da809fffaaa8865f9a07ace8b19d5b28cd492ae0c28f54b279e4e1c4e07f55831a4d40e70f50f6926707be042909ef8bab6fbde13811817143e929f6e0705c

test:
  secret_key_base: 2841eaebb583d740050ec56fef028a4f988815c9caf2860ee2531bfb6f6204c7dd151fbfbe405c40bf794a6fd317e7714d285846fd56b8362e35ef1bfc1bbe39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
